// <auto-generated />
using System;
using Exam.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230405210143_AddDescriptionToGoods")]
    partial class AddDescriptionToGoods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam.Database.Enitites.CheckEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<long>("SupermarketFK")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupermarketFK");

                    b.ToTable("Checks", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.GoodsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<long?>("CheckFK")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<long>("SupermarketFK")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckFK");

                    b.HasIndex("SupermarketFK");

                    b.ToTable("Goods", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<long?>("CheckFK")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<long>("SupermarketFK")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckFK");

                    b.HasIndex("SupermarketFK");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Supermarkets", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.CheckEntity", b =>
                {
                    b.HasOne("Exam.Database.Enitites.SupermarketEntity", "Supermarket")
                        .WithMany("Checks")
                        .HasForeignKey("SupermarketFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("Exam.Database.Enitites.GoodsEntity", b =>
                {
                    b.HasOne("Exam.Database.Enitites.CheckEntity", "Check")
                        .WithMany("Goods")
                        .HasForeignKey("CheckFK");

                    b.HasOne("Exam.Database.Enitites.SupermarketEntity", "Supermarket")
                        .WithMany("Goods")
                        .HasForeignKey("SupermarketFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("Exam.Database.Enitites.ProductEntity", b =>
                {
                    b.HasOne("Exam.Database.Enitites.CheckEntity", "Check")
                        .WithMany("Products")
                        .HasForeignKey("CheckFK");

                    b.HasOne("Exam.Database.Enitites.SupermarketEntity", "Supermarket")
                        .WithMany("Products")
                        .HasForeignKey("SupermarketFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("Exam.Database.Enitites.CheckEntity", b =>
                {
                    b.Navigation("Goods");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketEntity", b =>
                {
                    b.Navigation("Checks");

                    b.Navigation("Goods");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
