// <auto-generated />
using System;
using Exam.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230401093632_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam.Database.Enitites.GoodsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Goods", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.HasKey("Id");

                    b.ToTable("Supermarkets", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketGoodsEntity", b =>
                {
                    b.Property<long>("SupermarketFK")
                        .HasColumnType("bigint");

                    b.Property<long>("GoodsFK")
                        .HasColumnType("bigint");

                    b.HasKey("SupermarketFK", "GoodsFK");

                    b.HasIndex("GoodsFK");

                    b.ToTable("SupermarketGoods", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketProductsEntity", b =>
                {
                    b.Property<long>("ProductFK")
                        .HasColumnType("bigint");

                    b.Property<long>("SupermarketFK")
                        .HasColumnType("bigint");

                    b.HasKey("ProductFK", "SupermarketFK");

                    b.HasIndex("SupermarketFK");

                    b.ToTable("SupermarketProducts", (string)null);
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketGoodsEntity", b =>
                {
                    b.HasOne("Exam.Database.Enitites.GoodsEntity", "Goods")
                        .WithMany("SupermarketGoods")
                        .HasForeignKey("GoodsFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Database.Enitites.SupermarketEntity", "Supermarket")
                        .WithMany("SupermarketGoods")
                        .HasForeignKey("SupermarketFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketProductsEntity", b =>
                {
                    b.HasOne("Exam.Database.Enitites.ProductEntity", "Product")
                        .WithMany("SupermarketProducts")
                        .HasForeignKey("ProductFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Database.Enitites.SupermarketEntity", "Supermarket")
                        .WithMany("SupermarketProducts")
                        .HasForeignKey("SupermarketFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("Exam.Database.Enitites.GoodsEntity", b =>
                {
                    b.Navigation("SupermarketGoods");
                });

            modelBuilder.Entity("Exam.Database.Enitites.ProductEntity", b =>
                {
                    b.Navigation("SupermarketProducts");
                });

            modelBuilder.Entity("Exam.Database.Enitites.SupermarketEntity", b =>
                {
                    b.Navigation("SupermarketGoods");

                    b.Navigation("SupermarketProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
